phospr:
    resource: "@PhosprCoreBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_homepage:
    path:      /
    defaults:  { _controller: PhosprCoreBundle:Default:index }
