pengarwin:
    resource: "@PengarWinCoreBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_homepage:
    path:      /
    defaults:  { _controller: PengarWinCoreBundle:Default:index }
